### ISSUE TITLE
代码运行后，mtcnn_detector.py好像有问题，处理图像出错，这里检测是是项目中提供的test图片

### ISSUE THREAD

**Issue by MI-cpu-code** [yeyupiaoling/Age-Gender-MXNET#8]
loading model/model 200                                                                                                                                                         
[18:06:40] C:\Jenkins\workspace\mxnet-tag\mxnet\src\nnvm\legacy_json_util.cc:204: Warning: loading symbol saved by MXNet version 10501 with lower version of MXNet v10500. May cause undefined behavior. Please update MXNet if you encounter any issue
[18:15:11] C:\Jenkins\workspace\mxnet-tag\mxnet\src\nnvm\legacy_json_util.cc:209: Loading symbol saved by previous version v0.8.0. Attempting to upgrade...
[18:15:11] C:\Jenkins\workspace\mxnet-tag\mxnet\src\nnvm\legacy_json_util.cc:217: Symbol successfully upgraded!
[18:15:11] C:\Jenkins\workspace\mxnet-tag\mxnet\src\nnvm\legacy_json_util.cc:209: Loading symbol saved by previous version v0.8.0. Attempting to upgrade...
[18:15:11] C:\Jenkins\workspace\mxnet-tag\mxnet\src\nnvm\legacy_json_util.cc:217: Symbol successfully upgraded!
[18:15:11] C:\Jenkins\workspace\mxnet-tag\mxnet\src\nnvm\legacy_json_util.cc:209: Loading symbol saved by previous version v0.8.0. Attempting to upgrade...
[18:15:11] C:\Jenkins\workspace\mxnet-tag\mxnet\src\nnvm\legacy_json_util.cc:217: Symbol successfully upgraded!
[18:15:11] C:\Jenkins\workspace\mxnet-tag\mxnet\src\nnvm\legacy_json_util.cc:209: Loading symbol saved by previous version v0.8.0. Attempting to upgrade...
[18:15:11] C:\Jenkins\workspace\mxnet-tag\mxnet\src\nnvm\legacy_json_util.cc:217: Symbol successfully upgraded!
加载模型：mtcnn-model
Traceback (most recent call last):
  File "infer.py", line 136, in <module>
    main()
  File "infer.py", line 122, in main
    faces, bboxes, pointses = model.get_faces(img)
TypeError: cannot unpack non-iterable NoneType object

**Comment by yeyupiaoling** [comment]
@MI-cpu-code 已修复
